<a href="https://colab.research.google.com/github/ozj1/Machine_Learning_and_Data_Science_projects/blob/main/Chat-Bot_natural_language_processing/Chat_Bot_natural_language_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Loading the Data

We will be working with the Babi Data Set from Facebook Research.

Full Details: https://research.fb.com/downloads/babi/

- Jason Weston, Antoine Bordes, Sumit Chopra, Tomas Mikolov, Alexander M. Rush,
  "Towards AI-Complete Question Answering: A Set of Prerequisite Toy Tasks",
  http://arxiv.org/abs/1502.05698


In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [12]:
%pwd

'/content'

In [9]:
import pickle
import numpy as np

In [15]:
with open("drive/MyDrive/Dataset/chatbot_dataset/train_qa.txt", "rb") as fp:   # Unpickling
    train_data =  pickle.load(fp)

In [16]:
with open("drive/MyDrive/Dataset/chatbot_dataset/test_qa.txt", "rb") as fp:   # Unpickling
    test_data =  pickle.load(fp)

## understanding the dataset format, a short story, a question, and an answer Yes or No

In [18]:
print(type(test_data))
print(type(train_data))
print(len(test_data))
print(len(train_data))

<class 'list'>
<class 'list'>
1000
10000


In [19]:
train_data[0]

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [24]:
# reshaping to get the sentence
print(' '.join(train_data[0][0]))
print(' '.join(train_data[0][1]))
#now what is the answer?
print(train_data[0][2])

Mary moved to the bathroom . Sandra journeyed to the bedroom .
Is Sandra in the hallway ?
no


## Let's see how many unique words we have in the entire dataset using set() and unite them using union().

In [25]:
# Create a set that holds the vocab words
vocab = set()
all_data = test_data + train_data

for story, question , answer in all_data:
    # In case you don't know what a union of sets is:
    # https://www.programiz.com/python-programming/methods/set/union
    vocab = vocab.union(set(story))
    vocab = vocab.union(set(question))

#answer dataset only has two words, we add them
vocab.add('no')
vocab.add('yes')

vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [27]:
vocab_len = len(vocab) + 1 #we add an extra space to hold a 0 for Keras's pad_sequences
#we find the max size of a story
max_story_len = max([len(data[0]) for data in all_data])
print(max_story_len)
#we find the max size of a question in the dataset
max_question_len = max([len(data[1]) for data in all_data])
print(max_question_len)

156
6


## We vectorize the data so it can be understood by Keras.

In [32]:
# Reserve 0 for pad_sequences
vocab_size = len(vocab) + 1

from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

# integer encode sequences of words
tokenizer = Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

tokenizer.word_index

{'milk': 1,
 'john': 2,
 'no': 3,
 'is': 4,
 '?': 5,
 'kitchen': 6,
 'grabbed': 7,
 'back': 8,
 'daniel': 9,
 'took': 10,
 'picked': 11,
 'to': 12,
 'bathroom': 13,
 '.': 14,
 'travelled': 15,
 'sandra': 16,
 'in': 17,
 'went': 18,
 'put': 19,
 'moved': 20,
 'yes': 21,
 'garden': 22,
 'dropped': 23,
 'office': 24,
 'mary': 25,
 'football': 26,
 'apple': 27,
 'journeyed': 28,
 'down': 29,
 'there': 30,
 'the': 31,
 'bedroom': 32,
 'discarded': 33,
 'hallway': 34,
 'got': 35,
 'left': 36,
 'up': 37}

In [35]:
train_story_text = []
train_question_text = []
train_answers = []
# We make separate lists for story, query, and answer.
for story,question,answer in train_data:
    train_story_text.append(story)
    train_question_text.append(question)

In [36]:
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

print(len(train_story_text))
print(len(train_story_seq))

10000
10000


## Functionalize Vectorization

In [37]:
def vectorize_stories(data, word_index=tokenizer.word_index, max_story_len=max_story_len,max_question_len=max_question_len):
    '''
    INPUT: 
    
    data: consisting of Stories,Queries,and Answers
    word_index: word index dictionary from tokenizer
    max_story_len: the length of the longest story (used for pad_sequences function)
    max_question_len: length of the longest question (used for pad_sequences function)


    OUTPUT:
    
    Vectorizes the stories,questions, and answers into padded sequences. We first loop for every story, query , and
    answer in the data. Then we convert the raw words to an word index value. Then we append each set to their appropriate
    output list. Then once we have converted the words to numbers, we pad the sequences so they are all of equal length.
    
    Returns this in the form of a tuple (X,Xq,Y) (padded based on max lengths)
    '''
    
    
    # X = STORIES
    X = []
    # Xq = QUERY/QUESTION
    Xq = []
    # Y = CORRECT ANSWER
    Y = []
    
    
    for story, query, answer in data:
        
        # Grab the word index for every word in story
        x = [word_index[word.lower()] for word in story]
        # Grab the word index for every word in query
        xq = [word_index[word.lower()] for word in query]
        
        # Grab the Answers (either Yes/No so we don't need to use list comprehension here)
        # Index 0 is reserved so we're going to use + 1
        y = np.zeros(len(word_index) + 1)
        
        # Now that y is all zeros and we know its just Yes/No , we can use numpy logic to create this assignment
        #
        y[word_index[answer]] = 1
        
        # Append each set of story,query, and answer to their respective holding lists
        X.append(x)
        Xq.append(xq)
        Y.append(y)
        
    # Finally, pad the sequences based on their max length so the RNN can be trained on uniformly long sequences.
        
    # RETURN TUPLE FOR UNPACKING
    return (pad_sequences(X, maxlen=max_story_len),pad_sequences(Xq, maxlen=max_question_len), np.array(Y))

In [38]:
inputs_train, queries_train, answers_train = vectorize_stories(train_data)

In [39]:
inputs_test, queries_test, answers_test = vectorize_stories(test_data)

In [40]:
inputs_test

array([[ 0,  0,  0, ..., 31, 32, 14],
       [ 0,  0,  0, ..., 31, 22, 14],
       [ 0,  0,  0, ..., 31, 22, 14],
       ...,
       [ 0,  0,  0, ..., 31, 27, 14],
       [ 0,  0,  0, ..., 31, 22, 14],
       [ 0,  0,  0, ..., 27, 30, 14]], dtype=int32)

In [41]:
queries_test

array([[ 4,  2, 17, 31,  6,  5],
       [ 4,  2, 17, 31,  6,  5],
       [ 4,  2, 17, 31, 22,  5],
       ...,
       [ 4, 25, 17, 31, 32,  5],
       [ 4, 16, 17, 31, 22,  5],
       [ 4, 25, 17, 31, 22,  5]], dtype=int32)

In [42]:
answers_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [43]:
sum(answers_test)

array([  0.,   0.,   0., 503.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 497.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [44]:
tokenizer.word_index['yes']

21

In [45]:
tokenizer.word_index['no']

3

## Creating the Model

In [53]:
from keras.models import Sequential, Model
from tensorflow.keras.layers import Embedding
from keras.layers import Input, Activation, Dense, Permute, Dropout
from keras.layers import add, dot, concatenate
from keras.layers import LSTM

### Placeholders for Inputs

Recall we technically have two inputs, stories and questions. So we need to use placeholders. `Input()` is used to instantiate a Keras tensor.


In [54]:
input_sequence = Input((max_story_len,))
question = Input((max_question_len,))

## Encoders
we build the model as described in the paper 

* Sainbayar Sukhbaatar, Arthur Szlam, Jason Weston, Rob Fergus,
  "End-To-End Memory Networks",
  http://arxiv.org/abs/1503.08895
### Input Encoder m

In [55]:
# Input gets embedded to a sequence of vectors
input_encoder_m = Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_size,output_dim=64))
input_encoder_m.add(Dropout(0.3))

# This encoder will output:
# (samples, story_maxlen, embedding_dim)

### Input Encoder c

In [56]:
# embed the input into a sequence of vectors of size query_maxlen
input_encoder_c = Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_size,output_dim=max_question_len))
input_encoder_c.add(Dropout(0.3))
# output: (samples, story_maxlen, query_maxlen)

### Question Encoder

In [57]:
# embed the question into a sequence of vectors
question_encoder = Sequential()
question_encoder.add(Embedding(input_dim=vocab_size,
                               output_dim=64,
                               input_length=max_question_len))
question_encoder.add(Dropout(0.3))
# output: (samples, query_maxlen, embedding_dim)

### Encode the Sequences

In [58]:
# encode input sequence and questions (which are indices)
# to sequences of dense vectors
input_encoded_m = input_encoder_m(input_sequence)
input_encoded_c = input_encoder_c(input_sequence)
question_encoded = question_encoder(question)

##### Use dot product to compute the match between first input vector seq and the query

In [59]:
# shape: `(samples, story_maxlen, query_maxlen)`
match = dot([input_encoded_m, question_encoded], axes=(2, 2))
match = Activation('softmax')(match)

#### Add this match matrix with the second input vector sequence

In [60]:
# add the match matrix with the second input vector sequence
response = add([match, input_encoded_c])  # (samples, story_maxlen, query_maxlen)
response = Permute((2, 1))(response)  # (samples, query_maxlen, story_maxlen)

#### Concatenate

In [61]:
# concatenate the match matrix with the question vector sequence
answer = concatenate([response, question_encoded])

In [62]:
answer

<KerasTensor: shape=(None, 6, 220) dtype=float32 (created by layer 'concatenate')>

In [63]:
# Reduce with RNN (LSTM)
answer = LSTM(32)(answer)  # (samples, 32)

In [64]:
# Regularization with Dropout
answer = Dropout(0.5)(answer)
answer = Dense(vocab_size)(answer)  # (samples, vocab_size)

In [65]:
# we output a probability distribution over the vocabulary
answer = Activation('softmax')(answer)

# build the final model
model = Model([input_sequence, question], answer)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',
              metrics=['accuracy'])

In [66]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, 156)]        0           []                               
                                                                                                  
 input_4 (InputLayer)           [(None, 6)]          0           []                               
                                                                                                  
 sequential_1 (Sequential)      (None, None, 64)     2432        ['input_3[0][0]']                
                                                                                                  
 sequential_3 (Sequential)      (None, 6, 64)        2432        ['input_4[0][0]']                
                                                                                              

In [67]:
# train
history = model.fit([inputs_train, queries_train], answers_train,batch_size=32,epochs=120,validation_data=([inputs_test, queries_test], answers_test))

Epoch 1/120
313/313 [==============================] - 8s 16ms/step - loss: 0.9453 - accuracy: 0.4941 - val_loss: 0.6979 - val_accuracy: 0.4970
Epoch 2/120
313/313 [==============================] - 5s 17ms/step - loss: 0.7096 - accuracy: 0.4989 - val_loss: 0.6940 - val_accuracy: 0.5030
Epoch 3/120
313/313 [==============================] - 5s 17ms/step - loss: 0.6988 - accuracy: 0.5018 - val_loss: 0.7006 - val_accuracy: 0.4970
Epoch 4/120
313/313 [==============================] - 6s 20ms/step - loss: 0.6963 - accuracy: 0.4944 - val_loss: 0.6938 - val_accuracy: 0.4970
Epoch 5/120
313/313 [==============================] - 5s 15ms/step - loss: 0.6957 - accuracy: 0.4938 - val_loss: 0.6932 - val_accuracy: 0.5030
Epoch 6/120
313/313 [==============================] - 5s 16ms/step - loss: 0.6955 - accuracy: 0.4976 - val_loss: 0.6943 - val_accuracy: 0.4970
Epoch 7/120
313/313 [==============================] - 6s 18ms/step - loss: 0.6955 - accuracy: 0.4969 - val_loss: 0.6933 - val_accuracy: